[commands.swipe.three]
left_up = ""
right_up = ""
up = "xdotool key super+ctrl+Down"
left_down = ""
right_down = ""
down = "xdotool key super+ctrl+Up"
left = "xdotool key super+ctrl+Right"
right = "xdotool key super+ctrl+Left"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "xdotool key super+ctrl+shift+Down"
left_down = ""
right_down = ""
down = "xdotool key super+ctrl+shift+Up"
left = "xdotool key super+ctrl+shift+Right"
right = "xdotool key super+ctrl+shift+Left"