[commands.swipe.three]
left_up = ""
right_up = ""
up = "kwindesktopctl down --desktop"
left_down = ""
right_down = ""
down = "kwindesktopctl up --desktop"
left = "kwindesktopctl right --desktop"
right = "kwindesktopctl left --desktop"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "kwindesktopctl down --window"
left_down = ""
right_down = ""
down = "kwindesktopctl up --window"
left = "kwindesktopctl right --window"
right = "kwindesktopctl left --window"
